// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIPOTEK.Data;

#nullable disable

namespace SIPOTEK.Migrations
{
    [DbContext(typeof(SipotekDbContext))]
    partial class SipotekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIPOTEK.Models.Obat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BentukObat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("JenisObat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NamaObat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.Property<DateTime>("TglKadaluarsa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Obats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BentukObat = "Tablet",
                            Harga = 6000m,
                            JenisObat = "Analgesik",
                            NamaObat = "Paracetamol",
                            Stok = 20,
                            TglKadaluarsa = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BentukObat = "Kapsul",
                            Harga = 8000m,
                            JenisObat = "Antibiotik",
                            NamaObat = "Amoxicillin",
                            Stok = 30,
                            TglKadaluarsa = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BentukObat = "Sirup",
                            Harga = 18000m,
                            JenisObat = "Ekspektoran",
                            NamaObat = "OBH",
                            Stok = 40,
                            TglKadaluarsa = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SIPOTEK.Models.ObatKeluar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JumlahKeluar")
                        .HasColumnType("int");

                    b.Property<string>("NoTransaksi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ObatId")
                        .HasColumnType("int");

                    b.Property<string>("Pelanggan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TglKeluar")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObatId");

                    b.ToTable("ObatKeluars");
                });

            modelBuilder.Entity("SIPOTEK.Models.ObatMasuk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JumlahMasuk")
                        .HasColumnType("int");

                    b.Property<int>("ObatId")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TglKadaluarsaM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglMasuk")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalHarga")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObatId");

                    b.ToTable("ObatMasuks");
                });

            modelBuilder.Entity("SIPOTEK.Models.ObatKeluar", b =>
                {
                    b.HasOne("SIPOTEK.Models.Obat", "Obat")
                        .WithMany()
                        .HasForeignKey("ObatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obat");
                });

            modelBuilder.Entity("SIPOTEK.Models.ObatMasuk", b =>
                {
                    b.HasOne("SIPOTEK.Models.Obat", "Obat")
                        .WithMany()
                        .HasForeignKey("ObatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obat");
                });
#pragma warning restore 612, 618
        }
    }
}
